### ISSUE TITLE
not enough eggplant

### ISSUE THREAD

**Issue by ShawSumma** [trvv/vgore#2]
,,,,,,,..,,,,,,,,,,,,..................,,,............................,,,,,,,,,,,,,****,,,,,,.....................................................**////((((((
,,,,,,,..,,,,,,,,,,,,.............................................,,,,,,*********////////**,,,,...................................................,,////((((((
,,,,,,,..,,,,,,,,,,,,...................................,,,,,,,,,,****///////////((((((((//****,,,,,,.............................................,,**////////
,,,,,........,,,,..,,,,.................................,,********////((((((((///((((((((((////****,,,,,,,,,,.....................................,,**////////
,,,,,,,..............,,...............................,,****////(((((((((((((((((((((((((((////////**********,,...................................,,**////////
,,,,,,,,,,,,,.............................,,,,,,..,,,,****//((((((############(((((((((((((((((//////////////**,,.................................,,**////////
,,,,,,,,,,,,,,,...........................,,,,,,,,,,**////((((((#####################((((((((((((((((((//////****,,,,.............................,,**////////
,,,,,,,,,,,....,,.........................,,,,,,****//((((((((############%%%%%########((((((((####((((((((//////**,,,,...........................,,**////////
,,,,,,,,,......,,,,,,.....................,,,,****//((((((((##############%%%%%############((########((((((((((((//****,,,........................,,**//////((
,,,,,,,,,,,....,,,,,,,,,,.................,,****//((((((((################%%%%###############################((((((////*,,..........................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,.............,,,,//((((####((#######################################%%%%%%##############((((/**,,........................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,.............,,**((#######################################%%%%%%%%%%%%%%%%%%################(//**,,......................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,......,,....,**((####%%######################((((#####%%%%%%%%%%%%%%%%%%%%%%%%###############((//**,,....................,,//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,........,,*//####%%%%%%%%%%#######################%%%%%%&&&&%%%%%%%%%%%%%%%%%%%%%%#########((((//**,,..................,,//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,,,*((##%%%%%%%%##########################%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%##(((((((((((((**,,..................,,//((((((
,,,,,,,,,,,,,..,,,,,,,,,,,,........,,,,/##%%%%%%%%%%############%%%%##########%%%%%%%%%%%%%%%############%%%%%%######(((((((((//**..................,,//((((((
,,,,,,,,,,,,,..,,,,,,,,,,,,........,,,,/##%%%%%%%%%%############%%%%%%######%%%%%%%%%%%##%%%%%%####%%%%%%%%%%%%%%######(((((((//**,,................,,//((##((
,,,,,,,,,,,,,,,,,,,,,,,,,,,..........**(##%%%%%%%%##########################%%%%%%%%%######%%%%%%%%%%%%%%%%%%%%%%%%%%#######((((//,,................,,//((####
,,,,,,,,,,,,,,,,,,,,,,,,,,,........,,**(%%%%%%%%%%##########################%%%%%%%%%######%%%%%%%%%%%%%%%%%%%%%%%%%%%%#######((//**,,..............,,//((####
,,,,,,,,,,,,,,,,,,,....,,,,,,......,,**#%%%%%%%%%%########((((((#############################%%%%##################%%%%###########//**,,............,,**((####
,,,,,,,,,,,,,,,,,........,,,,,,....,,**#%%%%%%%%%%######(((((((((((((((((((((((####((((##############((((((((#####################((**,,..............**((####
,,,,,,,,,,,,,,,....................,,**#%%%%%%%%####((((((////////////(((((((((((((((((((((((((((((((((((((((((((###########((((((((//**..............**((####
,,,,,,,,,,,,,,,....................,,**#%%%%%%####((((///////////////////////////////////////////////////////((((((((#######((((((((//**,,............**((####
,,,,,,,,,,,,,,,,,..................,,//#%%%%%%####((////////***************************//////////******//////////(((((((((((((((((////**,,............**((####
,,,,,,,,,,,,,,,,,,,,,..............,,//%&&%%%%##((((////***********************,,********************************///////((((((((//////**,,............,,((####
,,,,,,,,,,,,,,,,,,,................,,((%&&%%%%##((////************************,,,,,,,,,*********************************//////////////**,,............,,//####
,,,,,,,,,,,,,......................**((%&&%%%%##((////************************,,,,,,,,,,,,,****************,,,,,,**,,,,*********//////**..............,,//####
,,,,,,,,,,,..................,,,,,,**((%&&%%%%##((//////***********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,********////,,..............,,//((((
,,,,,,,,,..................,,,,,,,,**##%%%%%%%##((////////*********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**//**,,..............,,**((((
,,,,,,,,,..................,,,,,,,,**##%%%%%%%##((////////*********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................**//((
,,,,,,,,,,,......,,................**((%%%%%%%##((//////////******************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****,,................,,////
,,,,,,,,,,,,,,,,,,,,,..............**((%%%%%##((((//////////******************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****,,................,,////
,,,,,,,,,,,,,,,,,,,,,..........,,..,,((%%%%%##((((////////////**************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,////
.,,,,,,,,,,,,,,,,,,,,........,,,,,,**((%%%%%##((////////////********,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,////
.,,,,,,,,,,......,,....,,..,,,,******//#%%%%##((////////////******,,,,,,,,,,,,,******,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,**//
,,,,,,,,,..........,,,,,,..,,**////////(##%%##((////////////*********************************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******..................,,**//
,,,,,,,,,,,......,,,,,,,,,,,,**((((////(######((/////////////////////////////////////******************,,,,,,,,,,,,,,,,,,,,,,,,,******..................,,**//
,,,,,,,,,,,......,,,,,,,,,,,,//((((/////((##((((////////////////////(((((((((((((((((////////******************,,,,,,,,,,,..,,,,****,,..................,,**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,//((///////((((((//////////////((((((((((((((((#####((((((((//////////////****************,,,,,,,,,****,,..................,,**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**//////(((((((//////////////((((((((###################((((((/////////////////////////////****,,,,****,,....................**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**////(((((((((//////////////((((######%%%%%%%%%%###########((((((//////////(((((((((((((((////******,,......................,,//
,,,,,,,,,,,..,,,,,,,,,,,,,,,,**////(((((((((////////////////((((###########################((((////////((((##########(((((////****,,......................,,//
,,,,,,,,,,,,,,,,,,,....,,,,,,,,**//(((((((////////////////////(((((((((((((((((((##########((////**////((###############((((//****,,......................,,**
,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,**//((((/////////////////////////////(((((((((((((((##((((((((//******//((####%%###########((//**,,........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,....,,**///////////////////////////////////////(((((((((((((((((((////**,,**//((########(((((((((((//**,,........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,**//////////////////////////////////////////////////////////**,,,,,,**//((((((((((/////////**,,..........................,,**
,,,,,,,,,,,..,,,,,,,,,,,,....,,,,**/////////////////////////////////*********************//****,,,,,,****////((((((/////******,,..........................,,**
,,,,,,,,,....,,,,,,,,,,,,,,....,,**///////////////////////////////*****************************,,,,,,,,******///////////****,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,......,,**///////////////////////////////***************************,,,,,,,,,,**********//*******,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,**/////////////////////////////***************************,,,,,,,,,,**,,,,,,***********,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,**///////////////////////////////***********//////********,,,,..,,,,,,**,,,,,,,,,,,****,,,,............................**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****///((((////////////////////////////****/////////******,,,,,,....,,********,,,,,,*****,,..............................**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**///((((((///////////////////////////////////////********,,,,......,,*****************,,,,..............................**
,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,****///((##((/////////////////////////////////////////********,,,,....,,****//***********,,,,..............................,,
,,,,,,,,,,,,,,,,,,,,,....,,,,,,,,****///((##((((/////////////////////////////////////////////****,,,,,,,,**////////*******,,,,..............................,,
,,,,,,,,,,,,,..,,,,,,....,,,,,,********/((##((((///////////////////////////////////((((((((((////**********//////////*****,,................................,,
,,,,,,,,,,,,,,,..,,,,,,,,,,,,**********/((####((///////////////////////////////////((((####((((((//////////////////////***,,................................,,
,,,,,,,,,,,,,,,..,,,,,,,,,,*************//((##((///////////////////////////////////((((((######((((((//////////////////*,,..................................,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,***********//((##((///////////////////////////////////////((((((((((((////********////////*,,..................................,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**********/////((((((//////((((//////////(((((((((((((((((((((((((((////*******************,,....................................
,,,........,,,,,,,,,,,,,,,,,,********///////((((((((//((((((((////////((((###########((((((((((((((//////////////*******,,....................................
,............,,,,,,,,******,,********///////((((((((((((((((((//((((((((((((#################((((((((((((((((//////*****,,....................................
,,,,,,,,,,,..,,,,,,,,******************///////(((((((((((((((((((((((((((((((((((((((((((######((((((((((((((//////****,,,....................................
,,,,,,,,,,,..,,,,,,,,******************///////((((((((((((((((((((((((((////(((((((((((((((((((((//////((//////////****,......................................
,,,,,,,,,,,,,,,,,,,,,**//***************//////((((####((((((((((((((((((////(((((((((((((((((((////////////////////****,,,....................................
,,,,,,,,,,,,,,,,,,,,,**////*************////////((######(((((((((((((((((((((((((((((((((((((((((//////////////////****,,,....................................
,,,,,,,,,,,,,,,,,,,,,**//////*************//////((((######(((((((((((((((((((((((((((((####((((((((((////////////////**,,,....................................
,,,,,,,,,,,,,,,,,,,,,**////////***********//////((((########(((((((((((((((((((((((((((####((((((((//////////////////***,,....................................
,,,,,,,,,,,,,,,,,,,,,**//((((//*********//////////((##########((((((((((//////(((((((((((((((((////////////*************,,,,........,,,,,,....................
,,,,,,,,,,,,,,,,,,,******((((((///////////////////((((##########((((((((/////////////////////////////////****,,,,,,*****,,,,,,......,,,,,,,,,,............,,**
,,,,,,,,,****,,,,,,******((((((/////////////////////((((##########((((((///////////////////******************,,,,,,,,,,,,,,,,,,,......,,,,,,,,,,........,,//((
,,,,,,,,,********,,******//((((////**///////////////((((############((((/////////////////////******************,,,,,,,,,******,,,,......,,,,,,,,,,,,,,,,//##%%
,,,,,,,,,****************//((##((//****///////////////((((##########((((((///////////////////************************,,*////**,,,,,,......,,,,,,,,,,**//##%%%%
,,,,,,,,,****************//((##((//****///////////////((((############((((((///////////////////*************************//((((//**,,,,......,,,,,,**//##%%%%%%
,,,,,,,,,****************//((((((////***////////////////((((((((((((####(((((((((//////////////////////*****************//####((****,,,,....,,,,**//####%%%%%%
,,,,,,,,,******************//((((((//***//////////////////(((((((((((((((((((((((((((((//////////////*******************//((####((**,,,,,,,,,,,,**((##%%%%%%%%
,,,,,,,,,******************//((((((////***////////////////(((((((((((((((((((((((((((////////((((////*******************//((((####//**,,,,,,,,**//##%%%%%%%%%%
,,,,,,,********************////((((((///****////////////////(((((((((((((((((((((((//////////((((//********************/((((((((##((//**,,,,,,**//##%%%%%%%%%%

**Comment by 0paIescent** [comment]
``,,,,,,,....,,,,,,,,,,........,,........,.........................................,,,,,,,,.........................................................**//((((((((
,,,,,,,..,,,,,,,,,,,,..................,,,............................,,,,,,,,,,,,,****,,,,,,.....................................................**////((((((
,,,,,,,..,,,,,,,,,,,,.............................................,,,,,,*********////////**,,,,...................................................,,////((((((
,,,,,,,..,,,,,,,,,,,,...................................,,,,,,,,,,****///////////((((((((//****,,,,,,.............................................,,**////////
,,,,,........,,,,..,,,,.................................,,********////((((((((///((((((((((////****,,,,,,,,,,.....................................,,**////////
,,,,,,,..............,,...............................,,****////(((((((((((((((((((((((((((////////**********,,...................................,,**////////
,,,,,,,,,,,,,.............................,,,,,,..,,,,****//((((((############(((((((((((((((((//////////////**,,.................................,,**////////
,,,,,,,,,,,,,,,...........................,,,,,,,,,,**////((((((#####################((((((((((((((((((//////****,,,,.............................,,**////////
,,,,,,,,,,,....,,.........................,,,,,,****//((((((((############%%%%%########((((((((####((((((((//////**,,,,...........................,,**////////
,,,,,,,,,......,,,,,,.....................,,,,****//((((((((##############%%%%%############((########((((((((((((//****,,,........................,,**//////((
,,,,,,,,,,,....,,,,,,,,,,.................,,****//((((((((################%%%%###############################((((((////*,,..........................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,.............,,,,//((((####((#######################################%%%%%%##############((((/**,,........................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,.............,,**((#######################################%%%%%%%%%%%%%%%%%%################(//**,,......................**//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,......,,....,**((####%%######################((((#####%%%%%%%%%%%%%%%%%%%%%%%%###############((//**,,....................,,//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,........,,*//####%%%%%%%%%%#######################%%%%%%&&&&%%%%%%%%%%%%%%%%%%%%%%#########((((//**,,..................,,//((((((
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,,,*((##%%%%%%%%##########################%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%##(((((((((((((**,,..................,,//((((((
,,,,,,,,,,,,,..,,,,,,,,,,,,........,,,,/##%%%%%%%%%%############%%%%##########%%%%%%%%%%%%%%%############%%%%%%######(((((((((//**..................,,//((((((
,,,,,,,,,,,,,..,,,,,,,,,,,,........,,,,/##%%%%%%%%%%############%%%%%%######%%%%%%%%%%%##%%%%%%####%%%%%%%%%%%%%%######(((((((//**,,................,,//((##((
,,,,,,,,,,,,,,,,,,,,,,,,,,,..........**(##%%%%%%%%##########################%%%%%%%%%######%%%%%%%%%%%%%%%%%%%%%%%%%%#######((((//,,................,,//((####
,,,,,,,,,,,,,,,,,,,,,,,,,,,........,,**(%%%%%%%%%%##########################%%%%%%%%%######%%%%%%%%%%%%%%%%%%%%%%%%%%%%#######((//**,,..............,,//((####
,,,,,,,,,,,,,,,,,,,....,,,,,,......,,**#%%%%%%%%%%########((((((#############################%%%%##################%%%%###########//**,,............,,**((####
,,,,,,,,,,,,,,,,,........,,,,,,....,,**#%%%%%%%%%%######(((((((((((((((((((((((####((((##############((((((((#####################((**,,..............**((####
,,,,,,,,,,,,,,,....................,,**#%%%%%%%%####((((((////////////(((((((((((((((((((((((((((((((((((((((((((###########((((((((//**..............**((####
,,,,,,,,,,,,,,,....................,,**#%%%%%%####((((///////////////////////////////////////////////////////((((((((#######((((((((//**,,............**((####
,,,,,,,,,,,,,,,,,..................,,//#%%%%%%####((////////***************************//////////******//////////(((((((((((((((((////**,,............**((####
,,,,,,,,,,,,,,,,,,,,,..............,,//%&&%%%%##((((////***********************,,********************************///////((((((((//////**,,............,,((####
,,,,,,,,,,,,,,,,,,,................,,((%&&%%%%##((////************************,,,,,,,,,*********************************//////////////**,,............,,//####
,,,,,,,,,,,,,......................**((%&&%%%%##((////************************,,,,,,,,,,,,,****************,,,,,,**,,,,*********//////**..............,,//####
,,,,,,,,,,,..................,,,,,,**((%&&%%%%##((//////***********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,********////,,..............,,//((((
,,,,,,,,,..................,,,,,,,,**##%%%%%%%##((////////*********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**//**,,..............,,**((((
,,,,,,,,,..................,,,,,,,,**##%%%%%%%##((////////*********************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................**//((
,,,,,,,,,,,......,,................**((%%%%%%%##((//////////******************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****,,................,,////
,,,,,,,,,,,,,,,,,,,,,..............**((%%%%%##((((//////////******************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****,,................,,////
,,,,,,,,,,,,,,,,,,,,,..........,,..,,((%%%%%##((((////////////**************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,////
.,,,,,,,,,,,,,,,,,,,,........,,,,,,**((%%%%%##((////////////********,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,////
.,,,,,,,,,,......,,....,,..,,,,******//#%%%%##((////////////******,,,,,,,,,,,,,******,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******,,................,,**//
,,,,,,,,,..........,,,,,,..,,**////////(##%%##((////////////*********************************,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,******..................,,**//
,,,,,,,,,,,......,,,,,,,,,,,,**((((////(######((/////////////////////////////////////******************,,,,,,,,,,,,,,,,,,,,,,,,,******..................,,**//
,,,,,,,,,,,......,,,,,,,,,,,,//((((/////((##((((////////////////////(((((((((((((((((////////******************,,,,,,,,,,,..,,,,****,,..................,,**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,//((///////((((((//////////////((((((((((((((((#####((((((((//////////////****************,,,,,,,,,****,,..................,,**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**//////(((((((//////////////((((((((###################((((((/////////////////////////////****,,,,****,,....................**//
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**////(((((((((//////////////((((######%%%%%%%%%%###########((((((//////////(((((((((((((((////******,,......................,,//
,,,,,,,,,,,..,,,,,,,,,,,,,,,,**////(((((((((////////////////((((###########################((((////////((((##########(((((////****,,......................,,//
,,,,,,,,,,,,,,,,,,,....,,,,,,,,**//(((((((////////////////////(((((((((((((((((((##########((////**////((###############((((//****,,......................,,**
,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,**//((((/////////////////////////////(((((((((((((((##((((((((//******//((####%%###########((//**,,........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,....,,**///////////////////////////////////////(((((((((((((((((((////**,,**//((########(((((((((((//**,,........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,**//////////////////////////////////////////////////////////**,,,,,,**//((((((((((/////////**,,..........................,,**
,,,,,,,,,,,..,,,,,,,,,,,,....,,,,**/////////////////////////////////*********************//****,,,,,,****////((((((/////******,,..........................,,**
,,,,,,,,,....,,,,,,,,,,,,,,....,,**///////////////////////////////*****************************,,,,,,,,******///////////****,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,......,,**///////////////////////////////***************************,,,,,,,,,,**********//*******,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,**/////////////////////////////***************************,,,,,,,,,,**,,,,,,***********,,,,..........................,,**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,**///////////////////////////////***********//////********,,,,..,,,,,,**,,,,,,,,,,,****,,,,............................**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,****///((((////////////////////////////****/////////******,,,,,,....,,********,,,,,,*****,,..............................**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**///((((((///////////////////////////////////////********,,,,......,,*****************,,,,..............................**
,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,****///((##((/////////////////////////////////////////********,,,,....,,****//***********,,,,..............................,,
,,,,,,,,,,,,,,,,,,,,,....,,,,,,,,****///((##((((/////////////////////////////////////////////****,,,,,,,,**////////*******,,,,..............................,,
,,,,,,,,,,,,,..,,,,,,....,,,,,,********/((##((((///////////////////////////////////((((((((((////**********//////////*****,,................................,,
,,,,,,,,,,,,,,,..,,,,,,,,,,,,**********/((####((///////////////////////////////////((((####((((((//////////////////////***,,................................,,
,,,,,,,,,,,,,,,..,,,,,,,,,,*************//((##((///////////////////////////////////((((((######((((((//////////////////*,,..................................,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,***********//((##((///////////////////////////////////////((((((((((((////********////////*,,..................................,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,**********/////((((((//////((((//////////(((((((((((((((((((((((((((////*******************,,....................................
,,,........,,,,,,,,,,,,,,,,,,********///////((((((((//((((((((////////((((###########((((((((((((((//////////////*******,,....................................
,............,,,,,,,,******,,********///////((((((((((((((((((//((((((((((((#################((((((((((((((((//////*****,,....................................
,,,,,,,,,,,..,,,,,,,,******************///////(((((((((((((((((((((((((((((((((((((((((((######((((((((((((((//////****,,,....................................
,,,,,,,,,,,..,,,,,,,,******************///////((((((((((((((((((((((((((////(((((((((((((((((((((//////((//////////****,......................................
,,,,,,,,,,,,,,,,,,,,,**//***************//////((((####((((((((((((((((((////(((((((((((((((((((////////////////////****,,,....................................
,,,,,,,,,,,,,,,,,,,,,**////*************////////((######(((((((((((((((((((((((((((((((((((((((((//////////////////****,,,....................................
,,,,,,,,,,,,,,,,,,,,,**//////*************//////((((######(((((((((((((((((((((((((((((####((((((((((////////////////**,,,....................................
,,,,,,,,,,,,,,,,,,,,,**////////***********//////((((########(((((((((((((((((((((((((((####((((((((//////////////////***,,....................................
,,,,,,,,,,,,,,,,,,,,,**//((((//*********//////////((##########((((((((((//////(((((((((((((((((////////////*************,,,,........,,,,,,....................
,,,,,,,,,,,,,,,,,,,******((((((///////////////////((((##########((((((((/////////////////////////////////****,,,,,,*****,,,,,,......,,,,,,,,,,............,,**
,,,,,,,,,****,,,,,,******((((((/////////////////////((((##########((((((///////////////////******************,,,,,,,,,,,,,,,,,,,......,,,,,,,,,,........,,//((
,,,,,,,,,********,,******//((((////**///////////////((((############((((/////////////////////******************,,,,,,,,,******,,,,......,,,,,,,,,,,,,,,,//##%%
,,,,,,,,,****************//((##((//****///////////////((((##########((((((///////////////////************************,,*////**,,,,,,......,,,,,,,,,,**//##%%%%
,,,,,,,,,****************//((##((//****///////////////((((############((((((///////////////////*************************//((((//**,,,,......,,,,,,**//##%%%%%%
,,,,,,,,,****************//((((((////***////////////////((((((((((((####(((((((((//////////////////////*****************//####((****,,,,....,,,,**//####%%%%%%
,,,,,,,,,******************//((((((//***//////////////////(((((((((((((((((((((((((((((//////////////*******************//((####((**,,,,,,,,,,,,**((##%%%%%%%%
,,,,,,,,,******************//((((((////***////////////////(((((((((((((((((((((((((((////////((((////*******************//((((####//**,,,,,,,,**//##%%%%%%%%%%
,,,,,,,********************////((((((///****////////////////(((((((((((((((((((((((//////////((((//********************/((((((((##((//**,,,,,,**//##%%%%%%%%%%```
